title: "ASP.NET Image resizing for IIS"
subtitle: "URL-based image resizing has arrived, and it works with every language imaginable"
url: http://www.imageresizing.net/

# If you want to set the descrition or keywords meta tags on your site's
# home page, do it here.
#
#description: "I work with "
# keywords: "enter 3 or 4, comma separated, keywords"

# You should really specify your content's author when generating an
# Atom feed. Specify at least one of name, uri or email, and Nesta will
# include it in your feed. See the Atom spec for more info:
#
# http://www.atomenabled.org/developers/syndication/atom-format-spec.php#element.feed
#
author:
   name: Nathanael Jones
   uri: http://nathanaeljones.com
   email: n@imazen.io
   google_profile: "http://google.com/profiles/104429865496810073908"
   linkedin_profile: "http://www.linkedin.com/in/nathanaeljones"
   twitter_profile: "https://twitter.com/nathanaeljones"
   github_profile: "https://github.com/nathanaeljones"


disqus_short_name: resizer


content: content

production: 
  google_analytics_code: "UA-5218175-5"
  google_analytics_domain: "imageresizing.net" #Override domain for multiple subdomain support

# Google Webmaster and Analytics usually require a 'google[code].html' file be placed on the domain
# Use this feature to do this without polluting your directory structure
google_verify: [344a8f78fa8143f6, b4f699bd08907a51]



