title: "ASP.NET Image resizing for IIS"
subtitle: "URL-based image resizing has arrived, and it works with every language imaginable"
url: https://www.imageresizing.net/

# If you want to set the descrition or keywords meta tags on your site's
# home page, do it here.
#
#description: "I work with "
# keywords: "enter 3 or 4, comma separated, keywords"

# You should really specify your content's author when generating an
# Atom feed. Specify at least one of name, uri or email, and Nesta will
# include it in your feed. See the Atom spec for more info:
#
# http://www.atomenabled.org/developers/syndication/atom-format-spec.php#element.feed
#
author:
   name: Nathanael Jones
   uri: http://nathanaeljones.com
   email: support@imageresizing.net
   google_profile: "http://google.com/profiles/104429865496810073908"
   linkedin_profile: "http://www.linkedin.com/in/nathanaeljones"
   twitter_profile: "https://twitter.com/nathanaeljones"
   github_profile: "https://github.com/nathanaeljones"


github:
  editurl: https://github.com/imazen/resizer-web/edit/master/content
  showeditbutton: false

disqus_short_name: resizer


content: content

google_tag_manager: "GTM-5JKQ2GP"


# Google Webmaster and Analytics usually require a 'google[code].html' file be placed on the domain
# Use this feature to do this without polluting your directory structure
google_verify: [344a8f78fa8143f6, b4f699bd08907a51, 9fc94d97b09da6e4]
google_custom_search: "005556834036073640702:j3bnlceufnc"


categories:
- tag: benefits
  include: 
  - /benefits
  page: /
  meta: 
    prepend: /benefits/nav


- tag: docs
  include: 
  - /docs
  - /download
  - /plugins
  page: /docs
  meta: 
    sidebar: /docs/sidebar
    textclass: markdown-body
    
- tag: releases
  title: Releases
  include: /releases
  page: /releases
  meta:
    layout: release
    libs: plusone
    sidebar: /docs/sidebar





